version: SGLang v0.5.7
backend: openai
endpoint: /v1/chat/completions
trust-remote-code: true
ignore-eos: true
burstiness: 1.0
seed: 1
num-warmups: 0
metric-percentiles: "99"
temperature: 0.0
top-p: 1.0
top-k: -1
min-p: 0.0
frequency-penalty: 0.0
presence-penalty: 0.0
sharegpt-output-len: 128
max-model-len: 32768
mem-fraction-static: 0.90
